/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import game.Controller;
import game.Settings;

/**
 *
 * @author macbook
 */
public class StartDialog extends javax.swing.JDialog {

    /**
     * Creates new form StartDialog
     */
    public StartDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        setKeyBoard = new javax.swing.JButton();
        setMouse = new javax.swing.JButton();
        setBPanelButtons = new javax.swing.JButton();
        presentation = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        setKeyBoard.setText("Клавиатура");
        setKeyBoard.setActionCommand("setKeyBoard");
        setKeyBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setKeyBoardActionPerformed(evt);
            }
        });

        setMouse.setText("Мышь");
        setMouse.setActionCommand("Мышь");
        setMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMouseActionPerformed(evt);
            }
        });

        setBPanelButtons.setText("Панельные кнопки");
        setBPanelButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBPanelButtonsActionPerformed(evt);
            }
        });

        presentation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        presentation.setText("Выберите способ взаимодействия");

        jLabel2.setText("НОВАЯ ИГРА");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(setKeyBoard)
                .add(18, 18, 18)
                .add(setMouse)
                .add(18, 18, 18)
                .add(setBPanelButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(77, 77, 77)
                        .add(presentation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 244, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(153, 153, 153)
                        .add(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(presentation)
                .add(46, 46, 46)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(setKeyBoard)
                    .add(setMouse)
                    .add(setBPanelButtons))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMouseActionPerformed
        Settings.setAvailableControl(Controller.MOUSE_ON_FIELD);
        this.dispose();
    }//GEN-LAST:event_setMouseActionPerformed

    private void setKeyBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setKeyBoardActionPerformed
        Settings.setAvailableControl(Controller.KEYBOARD);
        this.dispose();
    }//GEN-LAST:event_setKeyBoardActionPerformed

    private void setBPanelButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBPanelButtonsActionPerformed
        Settings.setAvailableControl(Controller.PANEL_BUTTONS);
        this.dispose();
    }//GEN-LAST:event_setBPanelButtonsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel presentation;
    private javax.swing.JButton setBPanelButtons;
    private javax.swing.JButton setKeyBoard;
    private javax.swing.JButton setMouse;
    // End of variables declaration//GEN-END:variables
}
